config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :events, only: %i[new create index show edit update] do
    resources :uploads, only: %i[new create index]
    resources :messages, only: %i[create]
    resources :invitations, only: %i[create index]
    get "messages", to: 'messages#show', as: :chat
    post "invite/:user_id", to: 'invitations#create', as: :invite
  end

  patch "invitations/:id/accept", to: 'invitations#accept', as: :accept
  patch "invitations/:id/reject", to: 'invitations#reject', as: :reject
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :messages
  has_many :invitations
  has_many :invited_users, through: :invitations, source: :user
  has_one_attached :image

  validates :name, presence: true, length: { minimum: 5, maximum: 20 }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :image, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
  enum status: %i[pending accepted rejected]
  validates :user, uniqueness: { scope: :event, message: "user already invited" }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :event
  belongs_to :user
  validates :content, presence: true, length: { minimum: 1 }
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_many_attached :media
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :invitations
  has_many :events
  has_one_attached :profile_picture
  # has_many :events, through: :invitations
  has_many :events_as_guest, through: :invitations, source: :events
  validates :profile_picture, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :disable_nav, if: :devise_controller?


  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || events_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[nickname profile_picture])

    devise_parameter_sanitizer.permit(:account_update, keys: %i[nickname profile_picture])
  end

  def disable_nav
    @disable_nav_right = @disable_home = @back_home = true
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    start_date = params.fetch(:start_time, Date.today).to_date
    @events = Event.where(start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week).sort_by{|e| e.start_time}
    @invitations = Invitation.where(user: current_user).where(status: :pending)
    @invitations = @invitations.map{|i| i.event }.sort_by{|e| e.start_time }
    @upcoming_events = Invitation.where(user: current_user).where(status: :accepted)
    @upcoming_events = @upcoming_events.select{ |invitation| invitation.event.start_time > Date.today }.map { |i| i.event }.sort_by{|e| e.start_time }
    @disable_back = @disable_home = true
  end

  def show
    @event = Event.find(params[:id])
    @message = Message.new
    @invitation = Invitation.where(user: current_user).where(event: @event).first
    @uploads = Upload.where(event_id: params[:id])
    @disable_back = true
    @markers = {
      lat: @event.latitude,
      lng: @event.longitude
     }
  end

  def new
    @event = Event.new
    @disable_nav_right = @disable_home = true
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user

    if @event.save
      @invitation = Invitation.new(user:current_user, event:@event)
      @invitation.accepted!
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  private

  def event_params
    params.require(:event).permit(
      :name,
      :description,
      :location,
      :start_time,
      :end_time,
      :image
    )
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_event, only: %i[index create]
  before_action :set_invitation, only: %i[accept reject]

  def index
    @all_users = User.all
    @invitations = Invitation.where(event: @event)
    @invitation = Invitation.new
    @not_guests = User.where.not(id: @event.invitations.pluck(:user_id))
    @disable_nav_right = @disable_home = true
  end

  def create
    @user = User.find(params[:user_id])
    @invitation = Invitation.new(event: @event, user: @user)
    @invitation.save
    redirect_to event_invitations_path(@event)
  end

  def accept
    @invitation.accepted!
    redirect_to event_path(@invitation.event)
  end

  def reject
    @invitation.rejected!
    redirect_to events_path
  end

  private

  def set_invitation
    @invitation = Invitation.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_event

  def create
    @message = Message.new(message_params)
    @message.event = @event
    @message.user = current_user
    if @message.save
      EventChannel.broadcast_to(@event, render_to_string(partial: "message", locals: { message: @message }))
    end
  end

  def show
    @message = Message.new
    @disable_home = @disable_nav_right = true
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @disable_header = true
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  def index
    @uploads = Upload.where(event_id: params[:event_id])
  end

  def new
    @upload = Upload.new
    @event = Event.find(params[:event_id])
    @disable_nav_right = @disable_home = true
  end

  def create
    @upload = Upload.new(upload_params)
    @upload.user = current_user
    @upload.event = Event.find(params[:event_id])
    if @upload.save
      redirect_to event_path(@upload.event)
    elsif @upload.nil?
      render :new
    else
      render :new
    end
  end
end

  private

def upload_params
  params.require(:upload).permit(media: [])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def events_ajax_previous_link
    ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: true}
  end

  def events_ajax_next_link
    ->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, remote: true}
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="Vremennyy">
<meta name="application-name" content="Vremennyy">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/events/_attendees.html.erb
<% coming = Invitation.where(event_id: @event.id).accepted.size - 1 %>
<% attendees = Invitation.where(event_id: @event.id).pluck(:user_id, :status)%>
<% attendees = attendees.reject {|a| a[0] == @event.user.id } %>
  <p id="number" style="text-align: center"> <%= coming %> <%= coming !=1 ? " people are" : " person is" %> joining this event: </p>
<div id="accordion">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <div class="attendees">
        <% attendees.each do |attendee| %>
          <% if attendee[1] == "accepted" %>
            <div class="attending" style="background-image: url(<%= cl_image_path(User.find(attendee[0]).profile_picture.key) %>); background-size: cover">
              <p class="att-avatar"><%= User.find(attendee[0]).nickname.capitalize %></p>
            </div>
          <% end %>
        <% end %>
    </div>
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapsed collapse" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        <div class="attendees-list">
        <% attendees.each do |attendee| %>
          <% if attendee[1] == "accepted" %>
            <div class="attending" style="background-image: url(<%= cl_image_path(User.find(attendee[0]).profile_picture.key) %>); background-size: cover">
              <p class="att-avatar"><%= User.find(attendee[0]).nickname.capitalize %></p>
            </div>
          <% end %>
        <% end %>
    </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_calendar.html.erb
<div class="">
  <div class="swiper-header">
    <%= month_calendar events: events, previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |date, events| %>
      <%= date.day %>
        <% events.each do |event| %>
          <%= link_to event_path(event) do %>
          <div class="i-color" style="color:#14423f">
            <i class="fas fa-glass-cheers center"></i>
          </div>
          <% end %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/events/_event_details.html.erb
<div class="event-details">
      <div class="event-info">
        <div class="i-container">
          <i class="far fa-clock"></i>
        </div>
        <div>
          <p class="fatgrey"><%= @event.start_time.strftime("%d.%m.%Y") %></p>
          <p><%= @event.start_time.strftime("%H:%M") %></p>
        </div>
      </div>
      <div class="event-info">
        <div class="i-container">
          <i class="far fa-clock"></i>
        </div>
        <div>
          <p class="fatgrey"><%= @event.end_time.strftime("%d.%m.%Y") %></p>
          <p><%= @event.end_time.strftime("%H:%M") %></p>
        </div>
      </div>
      <div class="event-info">
        <div class="i-container">
          <i class="fas fa-map-marked"></i>
        </div>
        <div class="tacenter">
          <p><%= @event.location %></p>
        </div>
      </div>
      <div class="event-info">
        <div class="i-container">
          <i class="fas fa-info-circle"></i>
        </div>
        <div class="tacenter">
          <p><%= @event.description %></p>
        </div>
      </div>
    </div>

    <div style="text-align: center" >
      <%= link_to "Get directions","https://www.google.com/maps/search/?api=1&query=#{@event.latitude},#{@event.longitude}", class:"nbtn in-aubergine"%>
    </div>

    <div id="map"
      style="width: 100%;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">

    </div>

app/views/events/_eventcards.html.erb
<%= link_to event_path(event) do %>
  <div class="event-card">
    <div class="event-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(event.image.key) %>);">
    </div>

    <div class="inpic">
      <div class="event-date">
        <p class="day"> <%= event.start_time.strftime("%d") %> </p>
        <p><%= event.start_time.strftime("%b") %></p>
      </div>
      <%= cl_image_tag(event.user.profile_picture.key, class: "userpic") %>
    </div>

    <h2><%= event.name %></h2>
  </div>
<% end %>

app/views/events/_events_index.html.erb
<div class="wholepage-new">
  <div class="slidebar">
    <div class="border">
    </div>
  </div>
  <div class="outter-box-big" style="display: block">
    <div class="outter-box" style="display: block">
      <p class="titles"> UPCOMING EVENTS</p>
      <div class="upcoming" style="display: flex">
      <% if upcomings.size == 0 %>
        <p class="p">You have 0 Upcoming events.</p>
      <% else %>
        <% upcomings.each do |event|%>
          <% if event.start_time > Date.today %>
            <%= render "eventcards", event:event %>
          <% end %>
        <% end %>
      <% end %>
      </div>
    </div>
    <div class="outter-box" style="display: block">
      <p class="titles nomargin"> INVITATIONS </p>
      <div class="invitations" style="display: flex">
      <% if invitations.size == 0 %>
        <p class="p">You have 0 pending Invitations.</p>
      <% else %>
        <% invitations.each do |event|%>
          <% if event.start_time > Date.today %>
            <%= render "eventcards", event:event %>
          <% end %>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<h1 class="vform-title"><%= title %></h1>
<%= simple_form_for(event, html: { class: "vform"}) do |f| %>
  <div class="vform-group">
    <%= f.label :name %>
    <%= f.input :name, label: false, input_html: {class: "vinput"} %>
  </div>
  <%= f.file_field :image %>
  <div class="vform-group">
    <%= f.label :start_time %>
    <%= f.input :start_time, label: false, as: :string, input_html: {class: "datepicker vinput"} %>
  </div>
  <div class="vform-group">
    <%= f.label :end_time %>
    <%= f.input :end_time, label: false, as: :string, input_html: {class: "datepicker vinput"} %>
  </div>
  <div class="vform-group">
    <%= f.label :location %>
    <%= f.input :location, label: false, required: true, input_html: {id: "flat_address", class: "vinput"} %>
  </div>
  <div class="vform-group">
    <%= f.label :description %>
    <%= f.input :description, label: false, input_html: {class: "vinput"} %>
  </div>
  <%= f.submit class: "vform-submit" %>
<% end %>

app/views/events/_invited.html.erb
<div class="">
  <div class="swiper-header">
     <i class="fas fa-angle-double-left"></i>
     <h2>
       Your invitations
     </h2>
     <i class="fas fa-angle-double-right"></i>
  </div>
  <% invitations.each do |invitation| %>
    <% event = invitation.event %>
    <% if event.start_time > Date.today %>

      <%= link_to event_path(event) do %>
        <div class="event-card">
          <p class="event-date"><%= event.start_time.strftime("%d.%m.%Y") %></p>
          <div class="event-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), <%= "url(https://source.unsplash.com/random/#{rand(0..10000)})" %>">
            <h2><%= event.name %></h2>
          </div>
          <p class="event-host"><%= event.user.nickname %></p>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/events/_newform.html.erb
<div class="newform col-10">
  <%= simple_form_for([event], ) do |f| %>
    <%= f.input :name %>
    <%= f.input :start_time, :order => [:day, :month, :year] %>
    <%= f.input :end_time, :order => [:day, :month, :year] %>
    <%= f.input :location %>
    <%= f.input :description %>
    <%= f.submit "create", class: "btn create-btn" %>
  <% end %>
</div>

app/views/events/_past_show.html.erb
<% keys = [] %>
<% @uploads.each do |upload| %>
  <% upload.media.each do |image| %>
    <% keys << image.key %>
  <% end %>
<% end %>

<div class="upload-container">
  <% boxes = keys.each_slice(10).to_a %>
  <% boxes.each.with_index do |keys, index| %>
    <div class="uploads <%= index.even? ? "f-left" : "f-right" %>">
      <% keys.each_with_index do |key, index| %>
      <%= link_to cl_image_tag(key), event_uploads_path(@event, query: index)  %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= render "form", event:@event, title: "Edit Event" %>

app/views/events/index.html.erb
<div class="swiper verticalSwiper">
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      <div id="events_calendar">
        <%= render "calendar", events: @events %>
      </div>
    </div>
    <div class="swiper-slide">
      <%= render "events_index", invitations: @invitations, upcomings: @upcoming_events %>
    </div>
  </div>
</div>

app/views/events/index.js.erb
document.getElementById("#events_calendar").html("<%= escape_javascript render(partial: "calendar", locals: {events: @events}) %>");

app/views/events/new.html.erb
<%= render "form", event:@event, title: "New Event" %>

app/views/events/show.html.erb
<div class="event">
  <%= cl_image_tag(@event.image.key, class: "event-header") %>

  <div class="event-description">
    <h1 class="event-name"> <%= @event.name %></h1>
    <div class="event-host">
      <%= cl_image_tag(@event.user.profile_picture.key, class: "event-header") %>
      <p><%= @event.user.nickname %></p>
    </div>
    <div class="event-buttons">
      <%= link_to("chat", event_chat_path(@event), class: "nbtn n-aubergine") unless @event.start_time < Date.today %>
      <% if @event.user_id == current_user.id && @event.start_time > Date.today %>
        <%= link_to("invite", event_invitations_path(@event), method: :get, class: "nbtn n-darkgreyish")%>
      <% end %>
      <% if @invitation && @invitation.status == "pending" %>
        <%= link_to("accept", accept_path(@invitation), method: :patch, class: "nbtn n-darkgreyish") %>
        <%= link_to("reject", reject_path(@invitation), method: :patch, class: "nbtn n-paradiso") %>
      <% else %>
        <%= link_to("upload", new_event_upload_path(@event), class: "nbtn n-paradiso") %>
      <% end %>
    </div>

    <%= render 'events/attendees' %>
    <% if @event.start_time > Date.today %>
      <%= render 'events/event_details' %>
    <% end %>

  </div>
  <% if @event.start_time < Date.today %>
      <%= render 'events/past_show' %>
  <% end %>
</div>

app/views/invitations/index.html.erb
<h3 class="vform-title">Invitations</h3>

<div class="invitations-container">
  <% @all_users.each do |user| %>
    <% unless user == current_user %>
      <div class="invite-container">
        <%= cl_image_tag(user.profile_picture.key, class: "") %>
        <div>
          <p class="nickname"><%= user.nickname.capitalize %></p>
          <p class="email"><%= user.email %></p>
        </div>
        <% invitation = user.invitations.where(event_id: @event.id).first %>
        <% if invitation %>
          <% if invitation.status == "accepted" %>
            <i class="fas fa-check"></i>
          <% elsif invitation.status == "pending" %>
            <i class="fas fa-history"></i>
          <% elsif invitation.status == "rejected" %>
            <i class="fas fa-times"></i>
          <% end %>
        <% else %>
          <%= link_to(event_invite_path(@event, user), method: :post, remote: true) do %>
            <i class="fas fa-plus"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vrem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= stylesheet_pack_tag 'application' %>
    <meta name="apple-mobile-web-app-capable" content="yes">

    <%= render 'application/favicon' %>

  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/header' unless @disable_header%>
    <%= yield %>
  </body>

  <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

    <!-- Initialize Swiper -->


    <script>
      var swiper = new Swiper(".verticalSwiper", {
        direction: "vertical",
        slidesPerView: 1.2,
        initialSlide: 2,
        pagination: {
          el: ".swiper-pagination",
          clickable: true,
        },
      });
    </script>
</html>

app/views/messages/_message.html.erb
<% show_author = true if local_assigns[:show_author].nil? %>
<% user_class = message.user == current_user ? 'my-message' : 'others-message' %>
<% container_class = message.content.gsub(Unicode::Emoji::REGEX, "") == "" && message.content.scan(Unicode::Emoji::REGEX).count.between?(1, 3) ? "emoji" : "message" %>
<div class="<%= container_class%>-container" id="message-<%= message.id %>" data-user-id="<%= message.user.id %>">
  <p class="<%= user_class%>"><%= message.content %></p>
  <% if show_author %>
    <i class="nickname <%= user_class%>"><%= message.user.nickname %></i>
  <% end %>
</div>

app/views/messages/show.html.erb
<div id="chat">
  <div id="messages" data-event-id="<%= @event.id %>" data-current-user-id="<%= current_user.id %>">
    <% @event.messages.each_with_index do |message, index| %>
    <% hide_author = (@event.messages[index + 1] && @event.messages[index + 1].user == message.user) || current_user == message.user %>
      <%= render "messages/message", message:message, show_author: !hide_author %>
    <% end %>
  </div>
  <div class="chat-input">
    <%= simple_form_for [ @event, @message ], remote: true do |f| %>
      <%= f.input :content, label: false, placeholder: "Message ##{@event.name}" %>
    <% end %>
  </div>
</div>
<script>document.getElementById("messages").lastElementChild?.scrollIntoView();</script>

app/views/pages/home.html.erb
<div class="allofit">
  <div class="flexbox-home">
  <%= image_tag("logologo.png")%>

  <h1>Welcome</h1>
  <h6> to VREMENNYY</h6>
    <% if current_user.nil? %>
    <div class="links">
      <%= link_to((user_session_path), method: :get, :class => 'btn-boton') do %>
        Login
      <% end%>
    </div>
    <div class="links">
      <%= link_to((new_user_registration_path), method: :get, :class => 'btn-boton') do %>
        Sign UP
      <% end%>
    <% else %>
      <%= link_to((events_path), method: :get, :class => 'btn-boton') do %>
        Let´s go
      <% end%>
    <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <span></span>
</div>

app/views/shared/_header.html.erb
<header>
  <div class="header-group">
    <% unless @disable_back %>
      <% if @back_home %>
        <%= link_to(root_path, class:"header-link") do %>
          <i class="fas fa-angle-left"></i>
        <% end %>
      <% else %>
        <%= link_to('#',onclick: "javascript:history.go(-1); return false;", class:"header-link") do %>
          <i class="fas fa-angle-left"></i>
        <% end %>
      <% end%>
    <% end %>
      <% unless @disable_home %>
        <%= link_to(events_path, class:"header-link") do %>
          <i class="fas fa-home"></i>
        <% end%>
      <% end %>
  </div>
  <div class="header-group">
  <% unless @disable_nav_right %>
    <%= link_to(new_event_path, class:"header-link") do %>
        <i class="far fa-plus-square"></i>
    <% end%>

    <% if current_user %>
      <%= link_to(destroy_user_session_path, class:"header-link", method: :delete) do %>
        <i class="fas fa-user-times"></i>
      <% end%>
    <% else %>
      <%= link_to(new_user_session_path, class:"header-link") do %>
        <i class="fas fa-user"></i>
      <% end%>
    <% end %>
  <% end %>
  </div>
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/uploads/index.html.erb
<div class="swiper mySwiper">
  <div class="swiper-wrapper">
    <% @uploads.each do |upload| %>
      <% upload.media.each do |image| %>
        <div class="swiper-slide" id="<%= image.key %>"><%= cl_image_tag (image.key) %></div>
      <% end %>
    <% end %>
  </div>
  <div class="swiper-pagination"></div>
</div>

<script>
var urlString = window.location.href
var url = new URL(urlString);
var index = new Number(url.searchParams.get("query"));
index += 1

  var swiper = new Swiper(".mySwiper", {
    slidesPerView: 1,
    spaceBetween: 30,
    loop: true,
    pagination: {
      el: ".swiper-pagination",
      clickable: true,
    },
    navigation: {
      nextEl: ".swiper-button-next",
      prevEl: ".swiper-button-prev",
    },
  });
swiper.slideTo(index)

    </script>

app/views/uploads/new.html.erb
<div class="newuploadcontainer">
<h1>Upload images</h1>
  <%= simple_form_for [ @event, @upload ]  do |f| %>
    <%= f.file_field :media, multiple: true  %>
    <%= f.submit class: "vform-submit" %>

  <% end %>
</div>